spring.application.name=ticketReservation

spring.datasource.url=jdbc:postgresql://localhost:5432/ticket_reservation_db
spring.datasource.username=admin
spring.datasource.password=superpassword123



spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

application.security.jwt.secret-key = bXlTdXBlclNlY3JldEtleUZvckpXVFNpZ25pbmdXZWxsbGxvbmdFbm91Z2g=
